### ISSUE TITLE
any possibility to use U8g2 fonts?

### ISSUE THREAD

**Issue by wilsli** [michaelkamprath/Crystalfontz_ePaper_lib#3]
@michaelkamprath Thank you so much for this great driver for GDEW0213T5, I'm wondering if there is possibility to use U8g2_for_Adafruit to display unicode fonts.

**Comment by michaelkamprath** [comment]
So I am not deeply familiar with `U8g2_for_Adafruit`, but according to the [README](https://github.com/olikraus/U8g2_for_Adafruit_GFX) it says it can be used with any AdaFruit GFX derived library. This `ePaperDriveLib` is a AdaFruit GFX derived library. Have you tried following the instructions on the `U8g2_for_Adafruit` README?

**Comment by wilsli** [comment]
I'm supposed to "connect" the U8g2 to a GxEPD class(a subclass of Adafruit_GFX class) object, like:
```
...
GxEPD_class display(GxIO, Rst, Bsy);
U8G2_FOR_ADAFRUIT_GFX u8g2Fonts;
...
void setup(void) {
  display.init();
  u8g2Fonts.begin(display);
}
...
```
Is there any way to get such Adafruit_GFX object from ePaperDriver lib?

**Comment by michaelkamprath** [comment]
The `ePaperDisplay` object is a a Adafruit GFX derived "library". In [the GDEW0213T5  example](https://github.com/michaelkamprath/ePaperDriverLib/blob/master/examples/Good%20Display/GDEW0213T5/GDEW0213T5.ino#L11) is the pointer to the created `ePaperDisplay` object is called `device`.

**Comment by wilsli** [comment]
I tried:
```
ePaperDisplay *device;
U8G2_FOR_ADAFRUIT_GFX u8g2Fonts;
...
void setup() {
 device = new ePaperDisplay(...);
 Adafruit_GFX& display = *device;
 u8g2Fonts.begin(display);
 ...
}

void loop() {
 device->clearScreen();
 u8g2Fonts.setForegroundColor(0x00);
 u8g2Fonts.setBackgroundColor(0xff);
 u8g2Fonts.setFont(u8g2_font_helvR14_tf);
 u8g2Fonts.setCursor(10, 10);                 
 u8g2Fonts.print("Hello World!");
 device->refreshScreen();
 delay(10000);
}
```
The program can be compiled, but have no luck with displaying anything on the ePaper screen. Maybe U8g2 didn't successfully "connected" to the ePaperDisplay object. U8g2_for_Adafruit's example used `display.init()` and `dispaly.update()` to write on the screen, but ePaperDisplay didn't implement those methods. ^_^
Anyway, thank you very much for the ePaperDriver library and the discussion!

**Comment by michaelkamprath** [comment]
The functions `init()` and `update()` are not part of the GFX base class. The `U8g2_for_Adafruit` class use of those methods come from the specific class pertaining to the hardware they are using.

**Comment by wilsli** [comment]
> The functions `init()` and `update()` are not part of the GFX base class. The `U8g2_for_Adafruit` class use of those methods come from the specific class pertaining to the hardware they are using.

Yes, the U8g2_for_Adafruit's sample use GxEPD, a Adafruit_GFX based class, as the hardware driver. I figured that the functions of writing data to the RAM buffer and to the SPI hardware are separated into different methods in the GxEPD class, U8g2_for_Adafruit tapped into the RAM buffer modification part only and kept the SPI data writing part untouched, so it works fine with GxEPD class.
